from __future__ import annotations

import logging
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Tuple

import numpy as np
import planetary_computer
import rasterio
from pystac_client import Client
from rasterio.mask import mask as rio_clip
from rasterio.warp import transform_geom

# Importing the production contracts we built previously
from app.services.satellite.provider_contracts import (
    EarthObservationClient,
    ObservationContext,
    ReflectanceCube,
    SceneNotFoundError,
    EarthObservationError,
)

logger = logging.getLogger(__name__)

# Constants encapsulated to prevent global namespace pollution
_SENTINEL2_ASSET_MAPPING = {
    "blue_band": "B02",
    "green_band": "B03",
    "red_band": "B04",
    "red_edge_band": "B05",
    "nir_band": "B08",
    "swir_band": "B11",
}
_REFLECTANCE_DENOMINATOR = 10_000.0


class PlanetaryComputerGateway:
    """
    Production-grade STAC client for Microsoft Planetary Computer.
    Complies strictly with the EarthObservationClient protocol.
    """
    
    gateway_name = "microsoft-planetary-computer-v1"

    def __init__(self, endpoint_url: str = "https://planetarycomputer.microsoft.com/api/stac/v1") -> None:
        self._endpoint = endpoint_url
        self._stac_session: Client | None = None

    @property
    def _session(self) -> Client:
        """Lazy initialization of the STAC network client to minimize cold-start latency."""
        if self._stac_session is None:
            self._stac_session = Client.open(self._endpoint)
        return self._stac_session

    def retrieve_scene(
        self,
        *,
        spatial_bounds: Dict[str, Any],
        search_start: date,
        search_end: date,
        max_cloud_tolerance: float,
    ) -> ObservationContext:
        """
        Executes spatial-temporal querying against the Sentinel-2 L2A catalog.
        """
        temporal_window = f"{search_start.isoformat()}/{search_end.isoformat()}"

        try:
            query_results = self._session.search(
                collections=["sentinel-2-l2a"],
                intersects=spatial_bounds,
                datetime=temporal_window,
                query={"eo:cloud_cover": {"lt": max_cloud_tolerance}},
                limit=5,  # Reduced limit to speed up JSON payload parsing
            )
            matched_items = list(query_results.items())
        except Exception as api_err:
            raise EarthObservationError(f"STAC API query failed: {api_err}") from api_err

        if not matched_items:
            raise SceneNotFoundError(
                f"No usable Sentinel-2 L2A scenes found under {max_cloud_tolerance}% cloud cover "
                f"for the requested window: {temporal_window}."
            )

        # Select the most recent valid observation
        target_scene = matched_items[0]
        authenticated_scene = planetary_computer.sign(target_scene)

        try:
            data_cube = self._extract_spatial_matrices(authenticated_scene, spatial_bounds)
        except Exception as extraction_err:
            raise EarthObservationError(f"Raster extraction pipeline failed: {extraction_err}") from extraction_err

        # Safely parse timestamps ensuring UTC timezone awareness
        raw_dt = authenticated_scene.properties.get("datetime")
        if authenticated_scene.datetime:
            acquisition_time = authenticated_scene.datetime
        else:
            acquisition_time = datetime.fromisoformat(raw_dt.replace("Z", "+00:00"))
        
        if not acquisition_time.tzinfo:
            acquisition_time = acquisition_time.replace(tzinfo=timezone.utc)

        # Extract preview thumbnail if generated by provider
        assets = authenticated_scene.assets
        preview_link = assets["rendered_preview"].href if "rendered_preview" in assets else None

        return ObservationContext(
            data_cube=data_cube,
            asset_id=authenticated_scene.id,
            acquisition_timestamp=acquisition_time,
            cloud_fraction=float(authenticated_scene.properties.get("eo:cloud_cover", 0.0)),
            source_platform=authenticated_scene.properties.get("platform", "Sentinel-2"),
            preview_uri=preview_link,
            extended_metadata={
                "mgrs_grid": authenticated_scene.properties.get("s2:mgrs_tile"),
                "processing_baseline": authenticated_scene.properties.get("s2:processing_baseline"),
            }
        )

    def _extract_spatial_matrices(self, stac_item: Any, clipping_geometry: Dict[str, Any]) -> ReflectanceCube:
        """
        Downloads, clips, scales, and aligns required multispectral bands.
        """
        extracted_layers: Dict[str, Tuple[np.ndarray, np.ndarray]] = {}

        # 1. IO Bound: Fetch and clip rasters from blob storage
        with rasterio.Env(GDAL_HTTP_TIMEOUT="15", GDAL_HTTP_MAX_RETRY="2"):
            for cube_attr, stac_key in _SENTINEL2_ASSET_MAPPING.items():
                asset_uri = stac_item.assets[stac_key].href
                
                with rasterio.open(asset_uri) as dataset:
                    # Reproject GeoJSON bounds into the raster's native CRS
                    native_geom = transform_geom("EPSG:4326", dataset.crs, clipping_geometry)
                    
                    cropped_matrix, _ = rio_clip(
                        dataset,
                        [native_geom],
                        crop=True,
                        indexes=1,
                        filled=False
                    )
                    
                    # Scale physical reflectance and cast to memory-efficient float32
                    scaled_data = np.asarray(cropped_matrix, dtype=np.float32) / _REFLECTANCE_DENOMINATOR
                    
                    # Extract embedded nodata masks
                    if np.ma.isMaskedArray(cropped_matrix):
                        nodata_mask = np.ma.getmaskarray(cropped_matrix)
                    else:
                        nodata_mask = np.zeros(scaled_data.shape, dtype=bool)
                        
                    extracted_layers[cube_attr] = (scaled_data, nodata_mask)

        # 2. CPU Bound: Resolve spatial resolution mismatches (10m vs 20m bands)
        # Determine the highest resolution shape (largest matrix dimensions)
        anchor_shape = max((matrix.shape for matrix, _ in extracted_layers.values()), key=lambda s: s[0] * s[1])
        
        aligned_matrices: Dict[str, np.ndarray] = {}
        composite_valid_mask = np.ones(anchor_shape, dtype=bool)

        for attr_name, (matrix, mask) in extracted_layers.items():
            if matrix.shape != anchor_shape:
                matrix = self._fast_align(matrix, anchor_shape)
                mask = self._fast_align(mask, anchor_shape)
            
            # Inject NaN for masked/nodata pixels to prevent math errors downstream
            aligned_matrices[attr_name] = np.where(mask, np.nan, matrix)
            
            # Accumulate a universal validity mask
            composite_valid_mask &= (~mask) & np.isfinite(aligned_matrices[attr_name])

        return ReflectanceCube(
            blue=aligned_matrices["blue_band"],
            green=aligned_matrices["green_band"],
            red=aligned_matrices["red_band"],
            red_edge=aligned_matrices["red_edge_band"],
            nir=aligned_matrices["nir_band"],
            swir=aligned_matrices["swir_band"],
            valid_mask=composite_valid_mask,
            resolution=10.0  # Sentinel-2 anchor resolution
        )

    @staticmethod
    def _fast_align(source_matrix: np.ndarray, target_dimensions: Tuple[int, int]) -> np.ndarray:
        """
        High-performance nearest-neighbor resampling.
        Bypasses np.ix_ overhead used in legacy implementations.
        """
        target_y, target_x = target_dimensions
        src_y, src_x = source_matrix.shape
        
        # Calculate scaling ratios and generate flat coordinate arrays
        y_indices = (np.arange(target_y) * (src_y / target_y)).astype(np.int32)
        x_indices = (np.arange(target_x) * (src_x / target_x)).astype(np.int32)
        
        # Advanced integer indexing (faster than np.ix_ for this specific use case)
        return source_matrix[y_indices[:, None], x_indices]